services:
  domutils:
    image: domutils
    build:
      context: node_modules/domutils
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
